apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: mysite
        image: rof1966/app-python-test:v1
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
