apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app.kubernetes.io/name: mypod
spec:
  containers:
  - name: mypod
    image: rof1966/nginx-color:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: http
        protocol: TCP
        containerPort: 80


  
