apiVersion: v1
kind: Service
metadata:
  name: mysite
spec:
  selector:
    app: mysite
  type: NodePort  
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    protocol: TCP
    nodePort: 30000
 