FROM golang:1.20 as build

WORKDIR /build

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:3.20 as app

WORKDIR /app

COPY --from=build /build/main .

CMD ["./main"]

EXPOSE 8080

# Imagem final com multistage build 14MB