version: '3.8'
services:
  web:
    container_name: app-caos-web
    image: rof1966/app-caos:latest
    restart: always
    ports:
      - 8080:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s
    # cpusets: "0-1" não recomendado o uso, somente em casos especificos
    memswap_limit: 512m
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    
    