version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy
  
  web-blue-01:
    image: rof1966/nginx-color-bluelight:latest
    networks:
      - proxy
  web-blue-02:
    image: rof1966/nginx-color-bluelight:latest
    networks:
      - proxy

  web-orange-01:
    image: rof1966/nginx-color-orange:latest
    networks:
      - proxy
  web-orange-02:
    image: rof1966/nginx-color-orange:latest
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

